Detache strategy
BioPhoton/rx-angular pull request #290
Opened 2020-09-03 23:00 UTC by BioPhoton

2020-09-06 23:05 UTC, hoebbelsB requested changes
THX for updating the docs! I have reviewed most of it and got some suggestions!

2020-09-06 23:05 UTC, hoebbelsB commented on libs/template/docs/render-strategies.md
> +Only the template will not be updated.
```suggestion
Additional information about `detached` views:

* If a view is detached, its input bindings will still receive values
* Also any related code will get executed properly as well as using Angulars internal APIs such as `ViewChild`
* Detached views are not getting checked when their parent components call `detectChanges`
* `HostBindings` like `[class]` `@animation` ... are not getting updated properly, when the parent component does not detect a new change
```

2020-09-07 10:51 UTC, BioPhoton commented on libs/template/src/lib/render-strategies/strategies/detach-strategy.ts
> +    );
removed as it was useless for this manner

2020-09-07 15:49 UTC, hoebbelsB approved these changes
:1st_place_medal:

2020-09-07 15:49 UTC, merged