Poc rxfor
BioPhoton/rx-angular pull request #302
Opened 2020-09-08 00:10 UTC by hoebbelsB

Experimental PR for upcoming `*rxFor` Directive.

I have implemented a very basic approach to get an impression about what has to be done in order to render multiple templates on a per template basis.

* `yarn nx s experiments`
* navigate to `for-poc/basic` route

The other approach is more advanced and uses the `IterableDiffer` in order to keep track of changes coming from the input observable.

* `yarn nx s experiments`
* navigate to `for-poc/advanced` route

 In the example there is a button which leads to an immutable update of the source value. Try it out :)

2020-09-08 09:24 UTC, BioPhoton commented
Nice @hoebbelsB 

Could you check out #300 and add your example with the differ as 04 there?
Also please try to reduce the code to the minimal amount relevant for your example.

2020-09-08 09:25 UTC, BioPhoton requested changes
Nice!

Please reduce the code a lill as suggested. 

Also I think we can poc all features of the for in the experiments. 
I like the differ usage. We should definitely use it. :)

2020-09-09 23:53 UTC, hoebbelsB commented
> Nice!
> 
> Please reduce the code a lill as suggested.
> 
> Also I think we can poc all features of the for in the experiments.
> I like the differ usage. We should definitely use it. :)

 @BioPhoton I have just added the iterable version to your PR. Just plain inserted, not reduced. I will do that in the next session

2020-09-10 20:49 UTC, BioPhoton commented
Nice. Will close this one in favor of #300

2020-09-10 20:49 UTC, closed without merging